include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    missing_required_argument: error
    invalid_null_aware_operator: error

linter:
  rules:
    prefer_single_quotes: false
    avoid_print: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    sort_child_properties_last: true
    use_key_in_widget_constructors: true
    prefer_final_locals: true
    unnecessary_this: true
